import os
from typing import List

from fastapi import FastAPI

from services.shared.schemas_v1 import (
    AskRequest,
    AskResponse,
    EntityItem,
    FeatureContribution,
    HealthResponse,
    RiskBlock,
    SourceItem,
)


app = FastAPI(title="Clinical AI Orchestrator", version="0.1.0")


@app.get("/health", response_model=HealthResponse)
async def health() -> HealthResponse:
    return HealthResponse(service="orchestrator")


@app.post("/v1/ask", response_model=AskResponse)
async def ask(request: AskRequest) -> AskResponse:
    """
    Stub implementation of the LangGraph-based orchestrator.

    For Milestone 0 this returns a deterministic, fake response that conforms
    to the API contract so the rest of the platform can be exercised end-to-end.
    """

    # In future milestones this will call:
    # - pii-service (/v1/redact)
    # - ner-service (/v1/extract)
    # - retrieval-service (/v1/retrieve)
    # - scoring-service (/v1/score)
    # and compose a final answer.

    answer = (
        "This is a stubbed clinical answer generated by the orchestrator. "
        "In a real deployment this would be produced by an LLM using RAG over "
        "local guidelines and risk scoring models."
    )

    sources: List[SourceItem] = [
        SourceItem(
            source_id="pubmed:123",
            title="Stubbed Hypertension Guideline",
            url="https://example.org/pubmed/123",
            snippet="This is a placeholder snippet from a local guideline corpus.",
            score=0.82,
        )
    ]

    entities: List[EntityItem] = [
        EntityItem(type="DISEASE", text="hypertension", start=0, end=11, confidence=0.9),
    ]

    risk = RiskBlock(
        score=0.72,
        label="high",
        explanation=[
            FeatureContribution(feature="bp_high", contribution=0.18),
            FeatureContribution(feature="age_bucket_60_70", contribution=0.12),
        ],
    )

    return AskResponse(
        trace_id=request.trace_id,
        pii_redacted=True,
        answer=answer,
        sources=sources,
        entities=entities,
        risk=risk,
    )


if __name__ == "__main__":
    import uvicorn

    # Default to 8010 to match docker-compose and ORCHESTRATOR_URL
    port = int(os.getenv("ORCHESTRATOR_PORT", "8010"))
    uvicorn.run("app.main:app", host="0.0.0.0", port=port, reload=True)

